# Generated by Django 3.2.19 on 2024-05-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0049_extra_fields_db_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVSSRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(choices=[('3.0', '3.0'), ('3.1', '3.1'), ('4.0', '4.0')], help_text='Version of the CVSS (e.g., 3.0, 3.1, 4.0)', max_length=10, verbose_name='CVSS Version')),
                ('score', models.FloatField(help_text='CVSS score for the rating', verbose_name='CVSS Score')),
                ('vector', models.CharField(help_text='CVSS vector for the rating', max_length=255, verbose_name='CVSS Vector')),
            ],
            options={
                'verbose_name': 'CVSS Rating',
                'verbose_name_plural': 'CVSS Ratings',
            },
        ),
        migrations.AddField(
            model_name='finding',
            name='cvss_ratings',
            field=models.ManyToManyField(blank=True, related_name='findings', to='reporting.CVSSRating'),
        ),
        migrations.AddField(
            model_name='reportfindinglink',
            name='cvss_ratings',
            field=models.ManyToManyField(blank=True, related_name='findings_link', to='reporting.CVSSRating'),
        ),
    ]
